accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/',views.SignUpView.as_view(),name="signup"),
    path('logout/',views.LogOut,name="logout"),
    path('login/',views.LogIn,name="login"),
]

ask_question/urls.py
from django.urls import path
from . import views
  
app_name = 'ask_questions'
urlpatterns =[
    #submitting comment ajax
    path('answer/new_comment/',views.AnswerNewComment,name="answer_new_comment"),
    # question_upvotessss
    path('question/upvote/',views.Question_VoteView,name='question_vote'),
    # answer_upvotessss
    path('answer/upvote/',views.Answer_VoteView,name='answer_vote'),
    #question new comment submit url 
    path('question/new_comment/',views.Question_NewComment_View,name='question_new_comment'),
    
    path('ask/',views.ask_question,name='ask'),
    #questions list
    path('',views.QuestionsListView,name='question_list'),
    #my asked quetion url
    path('my_asked_quetions/',views.MyQuestionsListView,name='my_question_list'),
    path('my_answered_quetions/',views.MyAnswerListView,name='my_answer_list'),
    path('<int:pk>/answers/<slug:slug>/',views.AnswerView,name='answers'),
   
]

quans/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',include('ask_question.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>QuAns</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Abel&display=swap" rel="stylesheet">
  </head>
  <body>
    <!-- navbar -->
      <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <a class="nav_item navbar-brand mb-0 h1 " href="{% url 'ask_questions:question_list' %}">
          QuAns
        </a>

        <div class="container"> 
          <div style="text-align:center;">
            <div>
              <form  id="search" class="form-inline">
                <input id="query" style="max-width:500px" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
      </div>
      {% if request.user.is_authenticated %}
          <a class="nav_item  " href="{% url 'ask_questions:question_list' %}"><span style="color:white">Recent</span>  </a>
          <a class="nav_item  " href="{% url 'ask_questions:ask' %}" ><span style="color:white">New</span></a>
          <a class="nav_item  " href="{% url 'ask_questions:my_question_list' %}" ><span style="color:white">My questions</span></a>
          <a class="nav_item  " href="{% url 'ask_questions:my_answer_list' %}" ><span style="color:white">My answers</span></a>
          <a class="nav_item  " href="{% url 'accounts:logout' %}" > <span style="color:white">LogOut</span></a>
      {% else %}
          <a class="nav_item  " href="{% url 'accounts:login' %}" ><span style="color:white">Login</span> </a>
          <a class="nav_item  " href="{% url 'accounts:signup' %}" ><span style="color:white">SignUp</span> </a>
      {% endif %}
        </div>
     </nav>
     <div>
       {% if messages %}
      <ul class="messages">
        {% for message in messages %}
        <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %} 
     </div>
     <div id="inner" >
      {% block content %}
      {% endblock %}
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="/static/jquery.js"></script>
<script type="text/javascript" src="/static/js/ask_event.js" ></script>
<script type="text/javascript" src="/static/js/ask.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% block content %}
<div style="padding-top: 10%;" class="container ">
  <div class="shadow p-3 mb-5 bg-white rounded">
    <h4 style="text-align: center;">Login</h4>
  <div ><br>
    <div style="margin: 0 auto;min-width:500px; text-align:center">
      {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
          {% endfor %}
      </ul>
      {% endif %}
      <form  method="POST">
        {% csrf_token %}
         <span> Username </span> {{ form.username }} <br> <br>
         <span>Password  </span> {{ form.password }} <br> <br>
          <div  class="row">
            <div class="col"><input type="submit" value="Login" class="btn btn-primary"></div>
          </div>
      </form>
    </div>
  </div>
  </div>
</div>

{% endblock %}
 

templates/sellerview.html
{% extends 'base.html' %}
{% block content %}
<div style="margin-top: 10%;text-align:center" class="container ">
    <div >
        <div>
            <a href="{% url 'accounts:itemform' %}">
              <button class="btn btn-primary">Add New Item</button>
            </a>
          </div>
          {% for item in item_list %}
          <div class=" col-3" data-catid="{{item.id}}" style="max-width: fit-content;margin-top:10px"  >
              <div style="height: 100%;background-color:#f0f0f5;" class="shadow p-1 mb-3 bg-white rounded" >
              <div style="background: url('{{item.picture.url}}') 100% 100% no-repeat;  background-size: cover;height:300px;width: 300px;">
                  {% if request.user == item.seller %}
                  <div style="margin-right:90%;margin-bottom:10px;">
                      <div class="dropdown">
                      <a  id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span style="font-weight: bolder;cursor: pointer;color:white; margin-left:1%;font-size:xx-large;">...</span>
                      </a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'accounts:update' item.id %}">Edit</a>
                        <a class="dropdown-item" href="{% url 'accounts:delete' item.id  %}">Delete</a>
                      </div>
                    </div>
                  </div>  
                  {% endif %}  
              </div>                                           
                  <div style="text-align: center;font-weight:bolder;">
                      {{item.item_name}}
                  </div> <br>
                  <div class="row" style="text-align: center;">
                      <div class="col">
                          ${{item.price}}
                      </div>
                      <div class="col">
                          {{item.quantity}} left
                      </div>
                      <div class="col">  
                          {% if request.user.is_authenticated %}                                                            
                          {% is_cart item.id request.user as cart_or_not %}
                          {% if  cart_or_not %}
                          <span class="add_cart" item_id="{{item.id}}"><button class="btn btn-info"><small id="add{{item.id}}">added</small> </button></span> 
                          {% else %}
                          <span class="add_cart" item_id="{{item.id}}"><button class="btn btn-info"><small id="add{{item.id}}">add</small> </button></span> 
                          {% endif %}
                          {% else %}
                          <a href="{% url 'accounts:login' %}"><button class="btn btn-info"><small id="add{{item.id}}">add</small> </button></a> 
                          {% endif %}
                      </div>
                      <div class="col">
                      <a href="{% url 'accounts:buy' item.id %}">buy</a>
                      </div>
                  </div>
                  <div class="more_info{{item.id}}">
                      <span style="font-weight: bold;"> seller :</span> 
                      {{item.seller}} <br>
                      <span style="font-weight: bold;">product description :</span>
                      {{item.item_description}} 
                  </div>
              </div>
          </div>
          {% empty %}
          <div>
             Opps! we don't have any product now ...
          </div>
          {% endfor  %}
    </div>
</div>
{% endblock %}
 

templates/signup_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
<div style="margin-top: 20%;"  class="shadow p-3 mb-5 bg-white rounded">
    <form  method="post">
        {% csrf_token %}
        <div>
           <span></span> {{form.username}} <br>
        </div>
        <div>
            <span> </span> {{form.email}} <br>
         </div>
         <div>
            <span> </span> {{form.first_name}} <br>
         </div>
         <div>
            <span> </span> {{form.last_name}} <br>
         </div>
         <div>
            <span></span> {{form.password1}} <br>
         </div>
         <div>
            <span> </span> {{form.password2}} <br>
         </div>
        <input class="btn btn-info" type="submit" name="signup">
    </form>
</div>
</div>
{% endblock %}